apiVersion: v1
kind: Pod
metadata: 
  name: app
  labels:
    app: app
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: app
      securityContext:
        runAsUser: 1000
      image: eu.gcr.io/nice-root-258809/app:latest
      ports:
      - containerPort: 5000
      env:
      - name: MY_SQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MY_SQL_USER
      - name: MY_SQL_DB
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MY_SQL_DB
      - name: MY_SQL_PASS
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MY_SQL_PASS
      - name: MY_SQL_HOST
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MY_SQL_HOST
      - name: KEY
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: KEY

---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
